---
title: 'New Post-doc Opportunity- Wessinger Lab'
---
<!--hello, this is an html comment--> 
<!--the title here NORMALLY controls the big text at the top of this web page as well as the title shown within the tab but I changed that so this title only controls the text within the tab for all .Rmds/.htmls (the change is coded within the in_header.html) because I wanted the information in the tab to say something different than the text at the top of each web page--> 
<br>
<!-- anything within carrots is html code that will by knitted into the .html output my knitting the .rmd-->
<!-- br means break and inserts an empty line, i think the size of the break is based on the default size of the body text-->

## Funding from the NSF and NIH MIRA program is allowing us to recruit two postdocs to join the lab!

The successful applicants will lead projects investigating these types of questions, with space to develop independent research directions:

  * What is the contribution of introgression to patterns of parallel trait evolution and speciation?
  * What is the genetic and genomic architecture for adaptive evolution?
  * How is complex trait variation maintained in recently diverged species?
  * What components of parallel evolution occur through similar genetic changes?

Expertise in population genomics, phylogenomic analyses, quantitative genetics, and fieldwork are a plus! (Any or all of these!)

Flexible start date and competitive salary.

Please email Carrie with a statement of interest or any questions! Thanks!