---
title: 'Current Research'
---

Our research investigates how genetic and ecological processes at the population level contribute to larger patterns and trends in complex trait evolution, specifically parallel evolution. Currently I'm exploring these issues in Penstemon, an emerging model system for floral evolution.

About Penstemon:
Penstemon is a large North American plant genus that is ancestrally adapted to bee pollination. Flowers adapted to hummingbird pollination have repeatedly evolved (an estimated 15-20 times!) through complex change to multiple floral traits, with little evidence of evolutionary reversals back to bee syndrome. Recent macroevolutionary analyses suggest hummingbird syndrome is associated with reduced diversification rate within Penstemon.

This impressive parallel evolution in a complex trait makes Penstemon a fantastic comparative system to study a variety of questions above and below the species level. We study these questions using a variety of approaches: population genomics, QTL mapping, quantitative genetics, comparative studies, phylogenetics, and modeling approaches.